[phases.setup]
nixPkgs = ['nodejs-22_x']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm run build']

[variables]
PORT = '8080'

[start]
cmd = 'pnpm run start'
